import { Theme } from '../themes/default';

export function generateInlineStyles(theme: Theme) {
  return {
    div: {
      fontFamily: theme.base.fontFamily,
      fontSize: theme.base.fontSize,
      lineHeight: theme.base.lineHeight,
      color: theme.base.color,
      letterSpacing: theme.base.letterSpacing,
      textAlign: theme.base.textAlign as 'justify',
    },
    h1: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.color,
      fontSize: theme.headings.h1.fontSize,
      margin: theme.headings.h1.margin,
      textAlign: theme.headings.h1.textAlign as 'center',
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
      borderBottom: theme.headings.h1.borderBottom,
      paddingBottom: theme.headings.h1.paddingBottom,
      position: theme.headings.h1.position as 'relative',
    },
    h2: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.color,
      fontSize: theme.headings.h2.fontSize,
      margin: theme.headings.h2.margin,
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
      borderLeft: theme.headings.h2.borderLeft,
      paddingLeft: theme.headings.h2.paddingLeft,
    },
    h3: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.color,
      fontSize: theme.headings.h3.fontSize,
      margin: theme.headings.h3.margin,
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
    },
    h4: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.color,
      fontSize: theme.headings.h4.fontSize,
      margin: theme.headings.h4.margin,
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
    },
    h5: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.color,
      fontSize: theme.headings.h5.fontSize,
      margin: theme.headings.h5.margin,
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
    },
    h6: {
      fontWeight: theme.headings.fontWeight,
      color: theme.headings.h6.color,
      fontSize: theme.headings.h6.fontSize,
      margin: theme.headings.h6.margin,
      lineHeight: '1.5',
      letterSpacing: theme.headings.letterSpacing,
    },
    p: {
      margin: theme.paragraph.margin,
      lineHeight: theme.paragraph.lineHeight,
    },
    img: {
      maxWidth: theme.image.maxWidth,
      height: 'auto',
      margin: theme.image.margin,
      display: 'block',
      borderRadius: theme.image.borderRadius,
    },
    pre: {
      fontFamily: theme.code.fontFamily,
      fontSize: theme.code.fontSize,
      lineHeight: theme.code.lineHeight,
      background: theme.code.block.background,
      padding: theme.code.block.padding,
      margin: theme.code.block.margin,
      borderRadius: theme.code.block.borderRadius,
      color: theme.code.block.color,
      overflow: 'auto',
    },
    codeInline: {
      fontFamily: theme.code.fontFamily,
      background: theme.code.inline.background,
      padding: theme.code.inline.padding,
      borderRadius: theme.code.inline.borderRadius,
      fontSize: '0.9em',
      color: theme.code.inline.color,
    },
    codeBlock: {
      fontFamily: theme.code.fontFamily,
    },
    table: {
      borderCollapse: 'collapse' as const,
      width: theme.table.width,
      margin: theme.table.margin,
      fontSize: theme.table.fontSize,
      borderSpacing: theme.table.borderSpacing,
      border: theme.table.border,
    },
    th: {
      border: theme.table.header.border,
      padding: theme.table.cell.padding,
      background: theme.table.header.background,
      fontWeight: theme.table.header.fontWeight,
    },
    td: {
      border: theme.table.cell.border,
      padding: theme.table.cell.padding,
    },
    blockquote: {
      margin: theme.blockquote.margin,
      padding: theme.blockquote.padding,
      background: theme.blockquote.background,
      borderRadius: theme.blockquote.borderRadius,
      color: theme.blockquote.color,
      borderLeft: theme.blockquote.borderLeft,
    },
    ul: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.unordered.listStyleType,
    },
    ol: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.ordered.listStyleType,
    },
    ulNested1: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.unordered.nestedLevel1.listStyleType,
    },
    ulNested2: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.unordered.nestedLevel2.listStyleType,
    },
    olNested1: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.ordered.nestedLevel1.listStyleType,
    },
    olNested2: {
      margin: theme.list.margin,
      padding: theme.list.padding,
      listStyleType: theme.list.ordered.nestedLevel2.listStyleType,
    },
    li: {
      margin: theme.list.item.margin,
      lineHeight: theme.list.item.lineHeight,
    },
    a: {
      color: theme.link.color,
      textDecoration: theme.link.textDecoration,
      borderBottom: theme.link.borderBottom,
    },
    hr: {
      margin: theme.hr.margin,
      border: 'none',
      borderTop: theme.hr.border,
    },
    strong: {
      color: theme.emphasis.strong.color,
      fontWeight: theme.emphasis.strong.fontWeight,
    },
    em: {
      color: theme.emphasis.em.color,
      fontStyle: theme.emphasis.em.fontStyle,
    },
    code: {
      fontFamily: theme.code.fontFamily,
      fontSize: theme.code.fontSize,
      lineHeight: theme.code.lineHeight,
      background: theme.code.inline.background,
      padding: theme.code.inline.padding,
      borderRadius: theme.code.inline.borderRadius,
      color: theme.code.inline.color,
    },
  };
}

